"""Interactive first-run setup for the MN5 helper scripts."""

from __future__ import annotations

import shlex
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
LAUNCH_ENV_PATH = SCRIPTS_DIR / ".launch.env"
BACKUP_ENV_PATH = SCRIPTS_DIR / ".launch.env.bak"
DEFAULT_REMOTE_LAUNCH_HOST = "alogin1.bsc.es"
DEFAULT_REMOTE_TRANSFER_HOST = "transfer1.bsc.es"
DEFAULT_REMOTE_INTERNET_HOST = "alogin4.bsc.es"
DEFAULT_REMOTE_ACCOUNT = "bsc70"
DEFAULT_LOCAL_PORT = "5678"
DEFAULT_UV_SYNC_ARGS = "--frozen"
DEFAULT_LIGHTWEIGHT_MODEL = "Llama-3.2-3B-Instruct"
DEFAULT_VLLM_IMAGE_PATH = "/gpfs/scratch/bsc70/singularity/vllm_openai_0.18.0.sif"
DEFAULT_MODEL_WEIGHTS_PARENT_DIR = (
    "/gpfs/scratch/bsc70/hpai/storage/projects/heka/models"
)
EXAMPLE_HEADER = (
    "# Generated by vec-inf-mn5-wizard.\n"
    "# Safe to edit later. Values exported in your shell still override this file.\n"
)


@dataclass(frozen=True)
class WizardConfig:
    """Resolved MN5 launcher settings."""

    remote_launch_host: str
    remote_transfer_host: str
    remote_internet_host: str
    remote_user: str
    model_name: str
    local_port: str
    auto_kill_stale_tunnel: str
    rsync_enabled: str
    rsync_src: str
    rsync_dest: str
    vec_inf_env: str
    vec_inf_config_dir_remote: str
    remote_work_dir: str
    remote_account: str
    remote_qos: str
    uv_sync_args: str
    job_start_timeout: str
    server_ready_timeout: str
    vec_inf_vllm_image_path: str
    vec_inf_cached_model_config_path: str
    vec_inf_model_weights_parent_dir: str


def parse_existing_launch_env(path: Path) -> dict[str, str]:
    """Load simple KEY=VALUE pairs from an existing .launch.env file."""
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, raw_value = line.split("=", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        if raw_value == "":
            values[key] = ""
            continue
        try:
            tokens = shlex.split(raw_value, posix=True)
        except ValueError:
            values[key] = raw_value.strip("\"'")
            continue
        values[key] = tokens[0] if len(tokens) == 1 else " ".join(tokens)
    return values


def build_defaults(
    remote_user: str,
    repo_name: str | None = None,
) -> dict[str, str]:
    """Build derived defaults from the user identity and local repo name."""
    repo_dir_name = repo_name or REPO_ROOT.name
    rsync_dest = f"/home/bsc/{remote_user}/repos/{repo_dir_name}"
    config_dir = f"{rsync_dest}/vec_inf/config/marenostrum5"
    remote_work_dir = f"/gpfs/scratch/bsc70/users/{remote_user}/vec-inf-work"
    return {
        "REMOTE_LAUNCH_HOST": DEFAULT_REMOTE_LAUNCH_HOST,
        "REMOTE_TRANSFER_HOST": DEFAULT_REMOTE_TRANSFER_HOST,
        "REMOTE_INTERNET_HOST": DEFAULT_REMOTE_INTERNET_HOST,
        "REMOTE_USER": remote_user,
        "MODEL_NAME": DEFAULT_LIGHTWEIGHT_MODEL,
        "LOCAL_PORT": DEFAULT_LOCAL_PORT,
        "AUTO_KILL_STALE_TUNNEL": "0",
        "RSYNC_ENABLED": "1",
        "RSYNC_SRC": ".",
        "RSYNC_DEST": rsync_dest,
        "VEC_INF_ENV": f"{rsync_dest}/.venv",
        "VEC_INF_CONFIG_DIR_REMOTE": config_dir,
        "REMOTE_WORK_DIR": remote_work_dir,
        "REMOTE_ACCOUNT": DEFAULT_REMOTE_ACCOUNT,
        "REMOTE_QOS": "",
        "UV_SYNC_ARGS": DEFAULT_UV_SYNC_ARGS,
        "JOB_START_TIMEOUT": "900",
        "SERVER_READY_TIMEOUT": "2000",
        "VEC_INF_VLLM_IMAGE_PATH": DEFAULT_VLLM_IMAGE_PATH,
        "VEC_INF_CACHED_MODEL_CONFIG_PATH": f"{config_dir}/models.yaml",
        "VEC_INF_MODEL_WEIGHTS_PARENT_DIR": DEFAULT_MODEL_WEIGHTS_PARENT_DIR,
    }


def prompt_with_help(
    console: Console,
    label: str,
    default: str,
    help_text: str,
    allow_empty: bool = False,
) -> str:
    """Prompt with a short explanation shown above the input."""
    console.print(f"[bold]{label}[/bold]")
    console.print(f"[dim]{help_text}[/dim]")
    while True:
        value = Prompt.ask(
            ">",
            default=default,
            show_default=True,
            console=console,
        ).strip()
        if value or allow_empty:
            return value
        console.print("[red]A value is required.[/red]")


def render_launch_env(config: WizardConfig) -> str:
    """Render the launcher configuration file."""
    lines = [
        EXAMPLE_HEADER.rstrip("\n"),
        "",
        "# MN5 host routing",
        f'REMOTE_LAUNCH_HOST="{config.remote_launch_host}"',
        f'REMOTE_TRANSFER_HOST="{config.remote_transfer_host}"',
        f'REMOTE_INTERNET_HOST="{config.remote_internet_host}"',
        "",
        "# Identity",
        f'REMOTE_USER="{config.remote_user}"',
        "",
        "# Default launch",
        f'MODEL_NAME="{config.model_name}"',
        f"LOCAL_PORT={config.local_port}",
        f"AUTO_KILL_STALE_TUNNEL={config.auto_kill_stale_tunnel}",
        "",
        "# Sync + remote environment",
        f"RSYNC_ENABLED={config.rsync_enabled}",
        f'RSYNC_SRC="{config.rsync_src}"',
        f'RSYNC_DEST="{config.rsync_dest}"',
        f'VEC_INF_ENV="{config.vec_inf_env}"',
        f'VEC_INF_CONFIG_DIR_REMOTE="{config.vec_inf_config_dir_remote}"',
        f'REMOTE_WORK_DIR="{config.remote_work_dir}"',
        f'REMOTE_ACCOUNT="{config.remote_account}"',
        f'REMOTE_QOS="{config.remote_qos}"',
        f'UV_SYNC_ARGS="{config.uv_sync_args}"',
        "",
        "# MN5 profile paths consumed by vec_inf/config/marenostrum5/environment.yaml",
        f'VEC_INF_VLLM_IMAGE_PATH="{config.vec_inf_vllm_image_path}"',
        f'VEC_INF_CACHED_MODEL_CONFIG_PATH="{config.vec_inf_cached_model_config_path}"',
        (
            'VEC_INF_MODEL_WEIGHTS_PARENT_DIR="'
            f'{config.vec_inf_model_weights_parent_dir}"'
        ),
        "",
        "# Timeouts",
        f"JOB_START_TIMEOUT={config.job_start_timeout}",
        f"SERVER_READY_TIMEOUT={config.server_ready_timeout}",
        "",
    ]
    return "\n".join(lines)


def write_launch_env(config: WizardConfig) -> None:
    """Write scripts/.launch.env, keeping a backup when replacing existing content."""
    content = render_launch_env(config)
    if LAUNCH_ENV_PATH.exists():
        previous = LAUNCH_ENV_PATH.read_text(encoding="utf-8")
        if previous != content:
            BACKUP_ENV_PATH.write_text(previous, encoding="utf-8")
    LAUNCH_ENV_PATH.write_text(content, encoding="utf-8")


def build_summary_table(config: WizardConfig) -> Table:
    """Render a concise summary table before writing files."""
    table = Table(show_header=False, box=None, pad_edge=False)
    table.add_column(style="bold cyan")
    table.add_column()
    table.add_row("Remote user", config.remote_user)
    table.add_row("Remote repo", config.rsync_dest)
    table.add_row("Remote venv", config.vec_inf_env)
    table.add_row("Config dir", config.vec_inf_config_dir_remote)
    table.add_row("Account", config.remote_account)
    table.add_row("Default model", config.model_name)
    table.add_row("vLLM image", config.vec_inf_vllm_image_path)
    table.add_row("Weights root", config.vec_inf_model_weights_parent_dir)
    return table


def build_effects_table(config: WizardConfig) -> Table:
    """Show exactly what the wizard will write before confirmation."""
    table = Table(title="File Effects", show_header=True, box=None, pad_edge=False)
    table.add_column("Action", style="bold cyan")
    table.add_column("Target / Effect")
    table.add_row("Write", str(LAUNCH_ENV_PATH.relative_to(REPO_ROOT)))
    if LAUNCH_ENV_PATH.exists():
        table.add_row("Backup", str(BACKUP_ENV_PATH.relative_to(REPO_ROOT)))
    table.add_row("Remote repo", config.rsync_dest)
    table.add_row("Remote venv", config.vec_inf_env)
    table.add_row("vLLM image", config.vec_inf_vllm_image_path)
    table.add_row("Weights root", config.vec_inf_model_weights_parent_dir)
    return table


def describe_setup_effects(config: WizardConfig) -> str:
    """Describe exactly what first_time_setup.sh will do."""
    return (
        "This will:\n"
        f"- create or reuse the remote checkout directory `{config.rsync_dest}`\n"
        f"- sync this local repo to `{config.remote_user}@{config.remote_transfer_host}:{config.rsync_dest}`\n"
        f"- connect to `{config.remote_internet_host}` and run `uv sync {config.uv_sync_args}` in that checkout\n"
        f"- create or update the remote environment at `{config.vec_inf_env}`\n"
        "Use `./scripts/first_time_setup.sh --dry-run` if you want a no-write preview."
    )


def describe_launch_effects(config: WizardConfig) -> str:
    """Describe exactly what launch_and_tunnel.sh will do."""
    return (
        "This will:\n"
        f"- submit a vec-inf launch for `{config.model_name}` via `{config.remote_launch_host}`\n"
        f"- use the MN5 config from `{config.vec_inf_config_dir_remote}`\n"
        f"- wait for the server to become ready\n"
        f"- open a local SSH tunnel on port `{config.local_port}` if launch succeeds"
    )


def preview_setup_execution(console: Console, config: WizardConfig) -> None:
    """Show the setup script preview before asking for final confirmation."""
    console.print()
    console.print(
        Panel.fit(
            describe_setup_effects(config),
            title="What first_time_setup.sh does",
            border_style="cyan",
        )
    )


def preview_launch_execution(console: Console, config: WizardConfig) -> None:
    """Show the launch script preview before asking for final confirmation."""
    console.print()
    console.print(
        Panel.fit(
            describe_launch_effects(config),
            title="What launch_and_tunnel.sh does",
            border_style="cyan",
        )
    )


def build_setup_run_prompt() -> str:
    """Return the setup execution confirmation prompt."""
    return "Run first_time_setup.sh now?"


def build_launch_run_prompt(model_name: str) -> str:
    """Return the launch execution confirmation prompt."""
    return f"Launch the smoke-test model `{model_name}` now?"


def ensure_local_commands(console: Console, command_names: list[str]) -> bool:
    """Check local command availability before running the helper scripts."""
    missing = [name for name in command_names if shutil.which(name) is None]
    if not missing:
        return True
    console.print(
        "[red]Missing local commands:[/red] " + ", ".join(missing) + ". "
        "Skipping the requested step."
    )
    return False


def run_helper_script(console: Console, script_name: str, *args: str) -> int:
    """Run one of the shell helpers from the repo root."""
    script_path = SCRIPTS_DIR / script_name
    console.print(
        f"\n[bold]Running[/bold] `{script_path.relative_to(REPO_ROOT)}` "
        + " ".join(args)
    )
    completed = subprocess.run(
        [str(script_path), *args],
        cwd=REPO_ROOT,
        check=False,
    )
    return completed.returncode


def prompt_for_config(console: Console, existing: dict[str, str]) -> WizardConfig:
    """Collect wizard inputs, using existing values when available."""
    console.print("[bold]MN5 setup[/bold] writes `scripts/.launch.env`.")
    if existing:
        console.print("[dim]Using current values from scripts/.launch.env as defaults.[/dim]")

    seed_user = existing.get("REMOTE_USER", "").strip()
    remote_user = prompt_with_help(
        console,
        "MN5 username",
        seed_user,
        "Used for ssh, rsync, and derived defaults such as "
        f"/home/bsc/<user>/repos/{REPO_ROOT.name}.",
    )
    defaults = build_defaults(remote_user)
    merged = {**defaults, **existing}
    merged["REMOTE_USER"] = remote_user
    merged["RSYNC_DEST"] = prompt_with_help(
        console,
        "Remote checkout path",
        defaults["RSYNC_DEST"],
        "Repo copy on MN5. Keeping it inside /home/bsc/<user>/repos/... avoids "
        "reusing older checkouts by accident.",
    )

    merged["REMOTE_ACCOUNT"] = prompt_with_help(
        console,
        "Slurm account",
        merged["REMOTE_ACCOUNT"] or DEFAULT_REMOTE_ACCOUNT,
        "Account passed to vec-inf launch. Default `bsc70` matches the current "
        "team examples in this repo.",
    )
    merged["VEC_INF_ENV"] = prompt_with_help(
        console,
        "Remote Python environment",
        f'{merged["RSYNC_DEST"]}/.venv',
        "Python venv on the MN5 login node used to run `vec-inf launch`. "
        "first_time_setup.sh creates it via `uv sync`. This is NOT the "
        "venv/container used on compute nodes (that comes from models.yaml).",
    )
    merged["VEC_INF_CONFIG_DIR_REMOTE"] = prompt_with_help(
        console,
        "Remote config directory",
        f'{merged["RSYNC_DEST"]}/vec_inf/config/marenostrum5',
        "Folder on MN5 containing environment.yaml and models.yaml. "
        "The launcher exports VEC_INF_CONFIG_DIR to this path on the login "
        "node so `vec-inf launch` reads the MN5 profile. Paths inside "
        "these YAMLs (image, weights, work_dir) are resolved there too.",
    )
    merged["REMOTE_WORK_DIR"] = prompt_with_help(
        console,
        "Remote work directory",
        merged.get("REMOTE_WORK_DIR") or defaults["REMOTE_WORK_DIR"],
        "Slurm --chdir for launched jobs. The job creates .vec-inf-cache/ "
        "here for compilation and tokenizer caches, so this should be on "
        "scratch (e.g. /gpfs/scratch/bsc70/users/<user>/vec-inf-work) to "
        "avoid filling the small MN5 home quota.",
    )
    merged["VEC_INF_VLLM_IMAGE_PATH"] = prompt_with_help(
        console,
        "Default vLLM image",
        defaults["VEC_INF_VLLM_IMAGE_PATH"],
        "Container image used by the MN5 profile for most launches. "
        "Set this to an existing SIF on MN5. The shared team default is "
        "vllm_openai_0.18.0.sif under /gpfs/scratch/bsc70/singularity/.",
    )
    merged["VEC_INF_MODEL_WEIGHTS_PARENT_DIR"] = prompt_with_help(
        console,
        "Model weights root",
        existing.get(
            "VEC_INF_MODEL_WEIGHTS_PARENT_DIR",
            defaults["VEC_INF_MODEL_WEIGHTS_PARENT_DIR"],
        ),
        "Parent directory containing model folders. The default points at the "
        "team weights path used in the current MN5 docs.",
    )

    if Confirm.ask(
        "Edit advanced options (hosts, local port, default model, QoS)?",
        default=False,
        console=console,
    ):
        merged["REMOTE_LAUNCH_HOST"] = prompt_with_help(
            console,
            "Launch host",
            merged["REMOTE_LAUNCH_HOST"],
            "Login node used for job submission and SSH tunneling.",
        )
        merged["REMOTE_TRANSFER_HOST"] = prompt_with_help(
            console,
            "Transfer host",
            merged["REMOTE_TRANSFER_HOST"],
            "Host used for rsync data transfers.",
        )
        merged["REMOTE_INTERNET_HOST"] = prompt_with_help(
            console,
            "Internet-enabled host",
            merged["REMOTE_INTERNET_HOST"],
            "Login node used by first_time_setup.sh for uv sync.",
        )
        merged["MODEL_NAME"] = prompt_with_help(
            console,
            "Default launch model",
            existing.get("MODEL_NAME", defaults["MODEL_NAME"]),
            "Used when launch_and_tunnel.sh runs without an explicit model name.",
        )
        merged["LOCAL_PORT"] = prompt_with_help(
            console,
            "Default local tunnel port",
            existing.get("LOCAL_PORT", defaults["LOCAL_PORT"]),
            "Port bound on your laptop/workstation when a tunnel is created.",
        )
        merged["REMOTE_QOS"] = prompt_with_help(
            console,
            "QoS override",
            existing.get("REMOTE_QOS", ""),
            "Optional Slurm QoS passed as --qos. Leave blank to use whatever the "
            "selected MN5 config already defines.",
            allow_empty=True,
        )
    else:
        merged["MODEL_NAME"] = existing.get("MODEL_NAME", defaults["MODEL_NAME"])
        merged["LOCAL_PORT"] = existing.get("LOCAL_PORT", defaults["LOCAL_PORT"])
        merged["REMOTE_QOS"] = existing.get("REMOTE_QOS", "")

    merged["VEC_INF_CACHED_MODEL_CONFIG_PATH"] = existing.get(
        "VEC_INF_CACHED_MODEL_CONFIG_PATH",
        f'{merged["VEC_INF_CONFIG_DIR_REMOTE"]}/models.yaml',
    )
    merged["RSYNC_ENABLED"] = existing.get("RSYNC_ENABLED", defaults["RSYNC_ENABLED"])
    merged["RSYNC_SRC"] = existing.get("RSYNC_SRC", defaults["RSYNC_SRC"])
    merged["AUTO_KILL_STALE_TUNNEL"] = existing.get(
        "AUTO_KILL_STALE_TUNNEL",
        defaults["AUTO_KILL_STALE_TUNNEL"],
    )
    merged["UV_SYNC_ARGS"] = existing.get("UV_SYNC_ARGS", defaults["UV_SYNC_ARGS"])
    merged["JOB_START_TIMEOUT"] = existing.get(
        "JOB_START_TIMEOUT",
        defaults["JOB_START_TIMEOUT"],
    )
    merged["SERVER_READY_TIMEOUT"] = existing.get(
        "SERVER_READY_TIMEOUT",
        defaults["SERVER_READY_TIMEOUT"],
    )

    return WizardConfig(
        remote_launch_host=merged["REMOTE_LAUNCH_HOST"],
        remote_transfer_host=merged["REMOTE_TRANSFER_HOST"],
        remote_internet_host=merged["REMOTE_INTERNET_HOST"],
        remote_user=merged["REMOTE_USER"],
        model_name=merged["MODEL_NAME"],
        local_port=merged["LOCAL_PORT"],
        auto_kill_stale_tunnel=merged["AUTO_KILL_STALE_TUNNEL"],
        rsync_enabled=merged["RSYNC_ENABLED"],
        rsync_src=merged["RSYNC_SRC"],
        rsync_dest=merged["RSYNC_DEST"],
        vec_inf_env=merged["VEC_INF_ENV"],
        vec_inf_config_dir_remote=merged["VEC_INF_CONFIG_DIR_REMOTE"],
        remote_work_dir=merged["REMOTE_WORK_DIR"],
        remote_account=merged["REMOTE_ACCOUNT"],
        remote_qos=merged["REMOTE_QOS"],
        uv_sync_args=merged["UV_SYNC_ARGS"],
        job_start_timeout=merged["JOB_START_TIMEOUT"],
        server_ready_timeout=merged["SERVER_READY_TIMEOUT"],
        vec_inf_vllm_image_path=merged["VEC_INF_VLLM_IMAGE_PATH"],
        vec_inf_cached_model_config_path=merged["VEC_INF_CACHED_MODEL_CONFIG_PATH"],
        vec_inf_model_weights_parent_dir=merged["VEC_INF_MODEL_WEIGHTS_PARENT_DIR"],
    )


def main() -> int:
    """Run the interactive wizard."""
    console = Console()
    existing = parse_existing_launch_env(LAUNCH_ENV_PATH)
    config = prompt_for_config(console, existing)
    run_setup = False
    run_launch = False

    console.print()
    console.print(build_summary_table(config))
    console.print()
    console.print(build_effects_table(config))
    console.print()
    if not Confirm.ask(
        f"Write {LAUNCH_ENV_PATH.relative_to(REPO_ROOT)} with these values?",
        default=True,
        console=console,
    ):
        console.print("[yellow]No files were changed.[/yellow]")
        return 1

    write_launch_env(config)
    console.print(
        f"[green]Wrote[/green] `{LAUNCH_ENV_PATH.relative_to(REPO_ROOT)}`."
    )
    if BACKUP_ENV_PATH.exists():
        console.print(
            f"[dim]Previous file saved to "
            f"{BACKUP_ENV_PATH.relative_to(REPO_ROOT)}.[/dim]"
        )

    preview_setup_execution(console, config)
    run_setup = Confirm.ask(build_setup_run_prompt(), default=True, console=console)
    setup_ok = True
    if run_setup:
        if ensure_local_commands(console, ["ssh", "rsync"]):
            setup_ok = (
                run_helper_script(console, "first_time_setup.sh") == 0
            )
        else:
            setup_ok = False

    run_launch = False
    if setup_ok:
        preview_launch_execution(console, config)
        run_launch = Confirm.ask(
            build_launch_run_prompt(config.model_name),
            default=False,
            console=console,
        )
    if run_launch and ensure_local_commands(console, ["ssh", "rsync"]):
        run_helper_script(
            console,
            "launch_and_tunnel.sh",
            config.model_name,
            config.local_port,
        )

    console.print(
        "\n[bold]Next commands[/bold]\n"
        f"  ./scripts/first_time_setup.sh\n"
        f"  ./scripts/launch_and_tunnel.sh {config.model_name} {config.local_port}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
